[versions]
mapstruct = "1.6.3"
quarkus = "3.18.2"
kotlin = "2.0.20"
dockerClient = "3.4.0"
flyway = "11.3.0"
jackson = "2.17.3"

[libraries]
quarkus-rest = { module = "io.quarkus:quarkus-rest", version.ref = "quarkus" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc", version.ref = "quarkus" }
quarkus-jdbc-postgresql = { module = "io.quarkus:quarkus-jdbc-postgresql", version.ref = "quarkus" }
quarkus-hibernate-orm-panache = { module = "io.quarkus:quarkus-hibernate-orm-panache", version.ref = "quarkus" }
quarkus-flyway = { module = "io.quarkus:quarkus-flyway", version.ref = "quarkus" }

[bundles]
quarkus = ["quarkus-rest", "quarkus-rest-jackson", "quarkus-arc", "quarkus-jdbc-postgresql", "quarkus-hibernate-orm-panache", "quarkus-flyway"]
